version: "3"
services:
  api:
    build: .
    container_name: api
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - 8081:5432
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080