create table person
(
    id integer generated by default as identity primary key,
    username varchar not null unique,
    password varchar not null,
    role varchar not null
);

create table tool
(
    id integer generated by default as identity primary key,
    person_id integer references person(id),
    tool_name varchar not null,
    cost integer
);

create table brand
(
    tools_id integer primary key references tool(id),
    brand_name varchar not null
);
