spring:
  application:
    name: CrudSecurityRestApplication
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none

jwt_secret: J37$Iv9*As6@